'use client';
import {useState,type FormEvent} from 'react';
import {ArrowUp,ArrowDown,Plus,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export type EtapaEditable={id?:string;nombre:string;tipo:string};
export function ConfigurarEtapas({etapas,onCerrar,onGuardar}:{etapas:EtapaEditable[];onCerrar:()=>void;onGuardar:(e:EtapaEditable[])=>Promise<void>}){
 const [filas,setFilas]=useState(()=>etapas.map((e,i)=>({...e,clave:e.id||'nueva-'+i}))),[error,setError]=useState(''),[ocupado,setOcupado]=useState(false);
 function mover(i:number,delta:number){setFilas(v=>{const a=[...v];[a[i],a[i+delta]]=[a[i+delta],a[i]];return a})}
 async function guardar(e:FormEvent){e.preventDefault();setError('');const limpias=filas.map(({id,nombre,tipo})=>({id,nombre:nombre.trim(),tipo}));if(limpias.some(e=>!e.nombre)||new Set(limpias.map(e=>e.nombre.toLocaleLowerCase('es'))).size!==limpias.length){setError('Cada etapa necesita un nombre distinto.');return}setOcupado(true);try{await onGuardar(limpias);onCerrar()}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar las etapas.')}finally{setOcupado(false)}}
 return <Dialog open onOpenChange={v=>{if(!v&&!ocupado)onCerrar()}}><DialogContent className="dialogo etapas-dialogo"><DialogTitle>Configurar etapas</DialogTitle><DialogDescription>Renombra, ordena o agrega etapas. Las existentes se conservan con su tipo para proteger el historial.</DialogDescription><form onSubmit={guardar}><fieldset disabled={ocupado}><div className="etapas-lista">{filas.map((e,i)=><div className="etapa-edicion" key={e.clave}><span className="etapa-numero">{i+1}</span><Input aria-label={'Nombre de etapa '+(i+1)} value={e.nombre} maxLength={80} required onChange={ev=>setFilas(v=>v.map(x=>x.clave===e.clave?{...x,nombre:ev.target.value}:x))}/>{e.id?<span className="etapa-tipo">{e.tipo==='abierta'?'Abierta':e.tipo==='ganada'?'Ganada':'Perdida'}</span>:<Select value={e.tipo} onValueChange={tipo=>setFilas(v=>v.map(x=>x.clave===e.clave?{...x,tipo}:x))}><SelectTrigger aria-label={'Tipo de etapa '+(i+1)}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="abierta">Abierta</SelectItem><SelectItem value="ganada">Ganada</SelectItem><SelectItem value="perdida">Perdida</SelectItem></SelectContent></Select>}<div className="etapa-orden"><Button type="button" variant="ghost" aria-label={'Subir etapa '+(i+1)} disabled={!i||ocupado} onClick={()=>mover(i,-1)}><ArrowUp size={17}/></Button><Button type="button" variant="ghost" aria-label={'Bajar etapa '+(i+1)} disabled={i===filas.length-1||ocupado} onClick={()=>mover(i,1)}><ArrowDown size={17}/></Button>{!e.id&&<Button type="button" variant="ghost" aria-label={'Quitar etapa '+(i+1)} onClick={()=>setFilas(v=>v.filter(x=>x.clave!==e.clave))}><X size={17}/></Button>}</div></div>)}</div><Button variant="outline" type="button" disabled={filas.length>=50||ocupado} onClick={()=>setFilas(v=>[...v,{clave:'nueva-'+Date.now()+'-'+Math.random(),nombre:'',tipo:'abierta'}])}><Plus size={17}/>Agregar etapa</Button></fieldset>{error&&<p className="mensaje-form es-error" role="alert">{error}</p>}<Button type="submit" className="boton principal" disabled={ocupado}>{ocupado?'Guardando…':'Guardar etapas'}</Button></form></DialogContent></Dialog>;
}
