"use client";
import catalogo from "@/shared/modulos.json";
import {Acceso} from "@/components/cuentas/acceso";
import {useEffect,useState,type FormEvent} from "react";
import {EnlaceModulo as Link} from "@/components/broquer/enlace-modulo";
import {ArrowUpRight,ArrowRight,ArrowLeft,CalendarDays,House,Users,FileText,Aperture,Megaphone,ContactRound,MessageCircle,ChartNoAxesCombined,Calculator,PenLine,Wallet,LayoutGrid,Search,SlidersHorizontal,Star,Plus,ChevronLeft,ChevronRight,MapPin,Clock,Check,ShieldCheck,LogIn,Mail,LoaderCircle,Info,LockKeyhole,CheckCheck} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Switch} from "@/components/ui/switch";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";

type Pantalla="inicio"|"agenda"|"campanas"|"herramientas"|"acceso";
type Modulo={clave:string;nombre:string;grupo:string;descripcion:string;icono:string;ruta_demo:string|null;estado_demo:string};
const iconos:Record<string,typeof House>={CalendarDays,House,Users,FileText,Aperture,Megaphone,ContactRound,MessageCircle,ChartNoAxesCombined,Calculator,PenLine,Wallet};
const predeterminados=["campanas","agenda","inmuebles","clientes","contratos","fotografia"];
const semana=[{dia:"Lun",numero:14},{dia:"Mar",numero:15},{dia:"Mié",numero:16},{dia:"Jue",numero:17},{dia:"Vie",numero:18},{dia:"Sáb",numero:19},{dia:"Dom",numero:20}];
const citas=[{id:1,dia:16,hora:"10:00",titulo:"Seguimiento con Mariana",detalle:"Llamada · Búsqueda de departamento",duracion:"30 minutos",tipo:"llamada"},{id:2,dia:16,hora:"12:30",titulo:"Visita en Altozano",detalle:"Casa del Encino · Con Sofía Ramírez",duracion:"45 minutos",tipo:"visita"},{id:3,dia:16,hora:"17:00",titulo:"Revisar propuesta de compra",detalle:"Con Daniel Torres",duracion:"30 minutos",tipo:"reunion"},{id:4,dia:17,hora:"11:00",titulo:"Segunda visita · Casa del Encino",detalle:"Con Sofía Ramírez",duracion:"45 minutos",tipo:"visita"}];
const nav=[{ruta:"/",id:"inicio",nombre:"Inicio",icono:House},{ruta:"/campanas",id:"campanas",nombre:"Campañas",icono:Megaphone},{ruta:"/agenda",id:"agenda",nombre:"Agenda",icono:CalendarDays},{ruta:"/herramientas",id:"herramientas",nombre:"Herramientas",icono:LayoutGrid}];
function Marca(){return <Link href="/" className="marca" aria-label="Broquer, inicio">broquer<span className="marca-punto"/></Link>}
function Boton({children,onClick,secondary=false,disabled=false,type="button"}:{children:React.ReactNode;onClick?:()=>void;secondary?:boolean;disabled?:boolean;type?:"button"|"submit"}){return <Button type={type} disabled={disabled} onClick={onClick} className={secondary?"boton secundario":"boton principal"}>{children}</Button>}
export function Espacio({pantalla}:{pantalla:Pantalla}){
 const [modulos,setModulos]=useState<Modulo[]>([]),[cargando,setCargando]=useState(true),[error,setError]=useState(false);
 const [favoritas,setFavoritas]=useState<string[]>(predeterminados),[preferenciasListas,setPreferenciasListas]=useState(false),[filtro,setFiltro]=useState("todas"),[busqueda,setBusqueda]=useState("");
 const [personalizar,setPersonalizar]=useState(false),[detalle,setDetalle]=useState<{titulo:string;texto:string}|null>(null),[dia,setDia]=useState(16);
 const [aviso,setAviso]=useState("");
 async function cargar(){setCargando(true);setError(false);try{setModulos(catalogo as Modulo[]);}catch{setError(true);}finally{setCargando(false);}}
 useEffect(()=>{void cargar();try{const saved=JSON.parse(localStorage.getItem("broquer.favoritas.v1")||"null");if(Array.isArray(saved)&&saved.every(x=>typeof x==="string"))setFavoritas(saved);}catch{}setPreferenciasListas(true);},[]);
 useEffect(()=>{if(preferenciasListas)try{localStorage.setItem("broquer.favoritas.v1",JSON.stringify(favoritas));}catch{setAviso("Este navegador no pudo guardar tus favoritas.");}},[favoritas,preferenciasListas]);
 const alternar=(clave:string)=>setFavoritas(v=>v.includes(clave)?v.filter(x=>x!==clave):[...v,clave]);
 const pendiente=(titulo:string)=>setDetalle({titulo,texto:"Esta función forma parte de Broquer y todavía está en construcción. En esta primera versión puedes explorar las pantallas y personalizar tus herramientas. No se guardan operaciones ni se hacen envíos reales."});
 const lista=modulos.filter(m=>(pantalla==="herramientas"||predeterminados.includes(m.clave)||filtro==="favoritas")&&(filtro!=="favoritas"||favoritas.includes(m.clave))&&`${m.nombre} ${m.descripcion} ${m.grupo}`.toLocaleLowerCase("es").includes(busqueda.toLocaleLowerCase("es")));
 const verCita=(c:typeof citas[number])=>setDetalle({titulo:c.titulo,texto:`${c.dia===16?"Miércoles":"Jueves"}, ${c.dia} de septiembre de 2026 · ${c.hora} · ${c.duracion}. ${c.detalle}. Zona horaria: America/Mexico_City. ${c.tipo==="visita"?"Ubicación de ejemplo: Altozano, Morelia. ":""}Esta es una cita ficticia de la demo; no envía recordatorios.`});
 return <>
 <a className="saltar" href="#contenido">Saltar al contenido</a>
 <header className="cabecera"><div className="cabecera-interior"><Marca/><nav className="navegacion" aria-label="Navegación principal">{nav.map(n=><Link key={n.id} href={n.ruta} aria-current={pantalla===n.id?"page":undefined}>{n.nombre}</Link>)}</nav><Link href="/acceso" className="acceso-link" aria-label="Mi cuenta"><span>Mi cuenta</span><span className="avatar" aria-hidden="true">A</span></Link></div></header>
 <div className="demo-bar"><div><span className="demo-etiqueta">Demo</span><span>Explora con datos de ejemplo.</span><button onClick={()=>setDetalle({titulo:"Un espacio para probar",texto:"Las personas, propiedades, citas y resultados son ficticios. Las favoritas se guardan únicamente en este navegador. El registro y las operaciones reales estarán disponibles cuando conectemos los servicios de Broquer."})} aria-label="Información de la demo"><Info size={16}/></button></div><Link href="/acceso">Acceder a mi cuenta <ArrowUpRight size={14}/></Link></div>
 <main id="contenido" className={`contenido pantalla-${pantalla}`}>
 {pantalla==="acceso"?<Acceso/>:<>
 <div className="titulo-fila"><div><p className="sobrelinea">{pantalla==="inicio"?"Miércoles, 16 de septiembre · Ejemplo":pantalla==="herramientas"?"Tu espacio, a tu manera":pantalla==="agenda"?"Mi semana":"Facebook e Instagram"}</p><h1>{pantalla==="inicio"?<>Buen día, Alex<span className="punto-naranja">.</span></>:pantalla==="herramientas"?"Tus herramientas":pantalla==="agenda"?"Tu agenda":"Campañas"}</h1>{pantalla==="inicio"&&<p className="subtitulo">Todo listo para tu siguiente paso.</p>}{pantalla==="herramientas"&&<p className="subtitulo">Elige las que hacen más fácil tu día.</p>}</div>{pantalla==="agenda"?<Boton onClick={()=>pendiente("Nueva cita")}><Plus size={19}/>Nueva cita</Boton>:pantalla==="campanas"?<Boton onClick={()=>pendiente("Nueva campaña")}><Plus size={19}/>Nueva campaña</Boton>:pantalla==="inicio"?<Link className="enlace-agenda" href="/agenda">Ver mi agenda <ArrowUpRight size={18}/></Link>:null}</div>
 {(pantalla==="inicio"||pantalla==="herramientas")&&<div className={pantalla==="inicio"?"inicio-columnas":"catalogo"}>
 {pantalla==="inicio"&&<aside className="columna-dia"><section className="visita"><div className="visita-cabecera"><span>Tu próxima visita</span><span className="etiqueta-hoy">Hoy</span></div><div className="foto-visita"><img src="/casa-demo.webp" alt="Casa ficticia de piedra clara y ventanales negros"/><span className="hora-foto"><Clock size={15}/>12:30 p. m.</span></div><div className="visita-cuerpo"><div className="ubicacion"><MapPin size={14}/>Altozano, Morelia</div><h2>Casa del Encino</h2><p>Visita con Sofía Ramírez</p><button className="visita-accion" onClick={()=>verCita(citas[1])}>Ver detalles <ArrowUpRight size={18}/></button></div></section><section className="hoy-lista"><div className="seccion-titulo"><h2>También hoy</h2><span>2 pendientes</span></div><button onClick={()=>verCita(citas[0])}><span className="reloj">10:00</span><span><strong>Llamar a Mariana</strong><small>Búsqueda de departamento</small></span><ChevronRight size={17}/></button><button onClick={()=>verCita(citas[2])}><span className="reloj">17:00</span><span><strong>Revisar propuesta</strong><small>Con Daniel Torres</small></span><ChevronRight size={17}/></button></section><div className="broq-nota"><span className="broq-icono">b.</span><div><strong>Broq, tu asistente</strong><p>Próximamente en tu espacio.</p></div><button aria-label="Conocer a Broq" onClick={()=>setDetalle({titulo:"Conoce a Broq",texto:"El asistente de Broquer te ayudará a encontrar información de tu negocio y preparar acciones. Todavía no está conectado a un modelo de IA. Cuando lo esté, respetará los permisos de tu cuenta y te pedirá confirmar los envíos y acciones sensibles."})}><ArrowUpRight size={19}/></button></div></aside>}
 <section className="herramientas-seccion"><div className="seccion-titulo"><h2>{pantalla==="inicio"?"Tus herramientas":"Explorar herramientas"}</h2><button className="texto-boton" onClick={()=>setPersonalizar(true)}><SlidersHorizontal size={16}/>Personalizar</button></div><div className="filtros"><Tabs value={filtro} onValueChange={setFiltro}><TabsList aria-label="Filtrar herramientas"><TabsTrigger value="todas">Todas</TabsTrigger><TabsTrigger value="favoritas">Favoritas <span className="cuenta">{favoritas.length}</span></TabsTrigger></TabsList></Tabs><label className="busqueda"><Search size={18}/><Input aria-label="Buscar herramienta" value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Buscar herramienta"/></label></div>
 {cargando?<div className="estado" role="status"><LoaderCircle className="girar"/>Cargando herramientas…</div>:error?<div className="estado"><p>No pudimos cargar tus herramientas.</p><Boton secondary onClick={()=>void cargar()}>Volver a intentar</Boton></div>:lista.length===0?<div className="estado"><Search/><h3>{filtro==="favoritas"&&!busqueda?"Tus favoritas empiezan aquí":"No encontramos esa herramienta"}</h3><p>{filtro==="favoritas"&&!busqueda?"Toca la estrella de una herramienta para guardarla.":"Prueba con otro nombre o explora todas."}</p><Boton secondary onClick={()=>{setFiltro("todas");setBusqueda("");}}>Ver todas</Boton></div>:<div className="herramientas-grid">{lista.map(m=>{const Icon=iconos[m.icono]||LayoutGrid;return <article key={m.clave} className={`tarjeta ${m.clave==="campanas"?"oscura":m.clave==="agenda"?"azul":""}`}><div className="tarjeta-superior"><span className="icono-modulo"><Icon size={24} strokeWidth={1.6}/></span><button className="estrella" aria-label={`${favoritas.includes(m.clave)?"Quitar":"Guardar"} ${m.nombre} ${favoritas.includes(m.clave)?"de":"en"} favoritas`} aria-pressed={favoritas.includes(m.clave)} onClick={()=>alternar(m.clave)}><Star size={19} fill={favoritas.includes(m.clave)?"currentColor":"none"} strokeWidth={1.5}/></button></div><h3>{m.ruta_demo?<Link className="tarjeta-enlace" href={m.ruta_demo}>{m.nombre}</Link>:m.nombre}</h3><p>{m.descripcion}</p>{m.ruta_demo?<span className="tarjeta-accion" aria-hidden="true">Explorar <ArrowUpRight size={18}/></span>:<button className="tarjeta-accion" onClick={()=>pendiente(m.nombre)}>Próximamente <Plus size={16}/><span className="sr-only">{m.nombre}</span></button>}</article>})}</div>}
 {pantalla==="inicio"&&<Link className="ver-todas" href="/herramientas"><LayoutGrid size={17}/>Explorar todas las herramientas<ArrowRight size={17}/></Link>}
 </section></div>}
 {pantalla==="agenda"&&<div className="agenda-columnas"><section><div className="mes-fila"><h2>Septiembre <span>2026</span></h2><span className="etiqueta-neutra">Semana de ejemplo</span></div><div className="semana" role="group" aria-label="Días de la semana">{semana.map(d=><button key={d.numero} aria-pressed={dia===d.numero} onClick={()=>setDia(d.numero)} className={dia===d.numero?"seleccionado":""}><span>{d.dia}</span><strong>{d.numero}</strong><span className={`marca-cita ${[16,17].includes(d.numero)?"tiene":""}`} aria-label={[16,17].includes(d.numero)?"Con citas":"Sin citas"}/></button>)}</div><div className="agenda-fecha"><h2>{semana.find(x=>x.numero===dia)?.dia}, {dia} de septiembre</h2><span>{citas.filter(c=>c.dia===dia).length} citas</span></div><div className="citas-lista">{citas.filter(c=>c.dia===dia).map(c=><div className="cita-fila" key={c.id}><time>{c.hora}</time><button className={`cita ${c.tipo==="visita"?"cita-visita":""}`} onClick={()=>verCita(c)}>{c.tipo==="visita"&&<img src="/casa-demo.webp" alt="Casa del Encino, propiedad de ejemplo"/>}<div><span className="cita-tipo">{c.tipo==="visita"?"Visita a propiedad":c.tipo==="llamada"?"Llamada":"Reunión"}</span><h3>{c.titulo}</h3><p>{c.detalle}</p><small><Clock size={14}/>{c.duracion}</small></div><ArrowUpRight size={18}/></button></div>)}{!citas.some(c=>c.dia===dia)&&<div className="estado"><CalendarDays size={32}/><h3>Un día sin citas</h3><p>Este día no tiene actividades en la agenda de ejemplo.</p></div>}</div><p className="zona-horaria">Horario de Ciudad de México · America/Mexico_City</p></section><aside className="agenda-lateral"><section className="pendientes"><h2>Por resolver</h2><p>Pequeños pasos para avanzar.</p>{["Enviar ficha a Mariana","Revisar documentos de Daniel","Preparar visita de mañana"].map((x,i)=><button key={x} onClick={()=>pendiente(x)}><span className="numero-pendiente">0{i+1}</span><span>{x}</span><ChevronRight size={16}/></button>)}</section><div className="bloque-tiempo"><Clock size={24}/><h3>Haz espacio para avanzar.</h3><p>Reserva un momento para el seguimiento de tus clientes.</p><button onClick={()=>pendiente("Reservar tiempo")}>Reservar tiempo<ArrowUpRight size={17}/></button></div></aside></div>}
 {pantalla==="campanas"&&<><div className="campana-periodo"><span>Resultados de ejemplo</span><span>Últimos 7 días · 10–16 sep 2026</span></div><div className="metricas"><div><span>Personas interesadas</span><strong>24</strong><small>Contactos recibidos</small></div><div><span>Inversión</span><strong>$1,680<span> MXN</span></strong><small>Importe ficticio · Sin cargos</small></div><div><span>Costo por contacto</span><strong>$70<span> MXN</span></strong><small>Inversión ÷ contactos</small></div></div><div className="campanas-columnas"><section><div className="seccion-titulo"><h2>Interés durante la semana</h2><span>Personas</span></div><div className="grafico" role="img" aria-label="Contactos de ejemplo por día: jueves 2, viernes 4, sábado 3, domingo 5, lunes 2, martes 4, miércoles 4; total 24.">{[2,4,3,5,2,4,4].map((v,i)=><div className="barra-columna" key={i}><span>{v}</span><div className={`barra ${i===6?"ultima":""}`} style={{height:`${v*24}px`}}/><small>{["Jue","Vie","Sáb","Dom","Lun","Mar","Mié"][i]}</small></div>)}</div><div className="seccion-titulo campañas-sub"><h2>Tus campañas</h2><span>1 de ejemplo</span></div><article className="campana-card"><img src="/casa-demo.webp" alt="Casa del Encino, inmueble ficticio"/><div className="campana-info"><span className="estado-campana">Ejemplo · Activa</span><h3>Casa del Encino</h3><p>Venta · Altozano, Morelia</p><div className="campana-datos"><span><strong>24</strong> contactos</span><span><strong>$240</strong> MXN / día</span></div><button className="texto-boton" onClick={()=>setDetalle({titulo:"Campaña de ejemplo",texto:"Objetivo: recibir contactos interesados. Inversión diaria ficticia: $240 MXN durante 7 días; total $1,680 MXN. Estos resultados no provienen de Meta. Para publicar anuncios reales, será necesario conectar tu cuenta y confirmar el presupuesto antes de cada publicación."})}>Ver campaña <ArrowUpRight size={16}/></button></div></article></section><aside className="conexion-meta"><span className="meta-icono" aria-hidden="true">f</span><h2>Tu próxima conversación empieza aquí.</h2><p>Conecta tus propiedades con personas que buscan su siguiente hogar.</p><div className="conexion-estado"><LockKeyhole size={17}/><span>Facebook no está conectado</span></div><Boton secondary onClick={()=>pendiente("Conectar Facebook e Instagram")}>Conectar mi cuenta<ArrowUpRight size={17}/></Boton><small>En esta demo no se publican anuncios ni se realiza ningún cargo.</small></aside></div></>}
 </>}
 <footer className="pie"><span>broquer<span className="punto-naranja">.</span></span><span>Tu trabajo, en un solo lugar.</span><button onClick={()=>setDetalle({titulo:"Primera etapa de Broquer",texto:"Esta entrega inicia los cimientos de la plataforma. Puedes explorar Inicio, Agenda y Campañas, buscar herramientas y guardar favoritas. Las operaciones reales, autenticación de producción y demás módulos todavía no están habilitados."})}>Versión en construcción <ArrowUpRight size={13}/></button></footer>
 </main>
 <nav className="navegacion-movil" aria-label="Navegación móvil">{nav.map(n=><Link key={n.id} href={n.ruta} aria-current={pantalla===n.id?"page":undefined}><n.icono size={21} strokeWidth={1.7}/><span>{n.nombre}</span></Link>)}</nav>
 <Dialog open={personalizar} onOpenChange={setPersonalizar}><DialogContent className="dialogo"><DialogTitle>Hazlo tuyo.</DialogTitle><DialogDescription>Guarda tus herramientas favoritas para encontrarlas más rápido.</DialogDescription><div className="personalizar-lista">{modulos.map(m=>{const Icon=iconos[m.icono]||House;return <label key={m.clave} className="personalizar-fila"><Icon size={20}/><span>{m.nombre}</span><Switch checked={favoritas.includes(m.clave)} onCheckedChange={()=>alternar(m.clave)} aria-label={`Guardar ${m.nombre}`}/></label>})}</div><Boton onClick={()=>setPersonalizar(false)}><Check size={18}/>Listo</Boton><p className="nota-pequena">Se guarda en este navegador.</p></DialogContent></Dialog>
 <Dialog open={!!detalle} onOpenChange={v=>{if(!v)setDetalle(null)}}><DialogContent className="dialogo"><DialogTitle>{detalle?.titulo}</DialogTitle><DialogDescription className="detalle-texto">{detalle?.texto}</DialogDescription><Boton onClick={()=>setDetalle(null)}>Entendido</Boton></DialogContent></Dialog>
 {aviso&&<div className="aviso" role="status">{aviso}<button onClick={()=>setAviso("")}>Cerrar</button></div>}
 </>;
}